[pytest]
markers = run
addopts = -s -v --reruns 2 --reruns-delay 3 --alluredir=allure-results --tb=short --color=no
testpaths = ./scripts
python_files = test_*.py
python_classes = Test*
python_functions = test_*